// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpcycjO5WJeB7X_RY68XNqpQqbsoKQ1pE',
    appId: '1:222984423696:web:f5e433a2458638510c7d95',
    messagingSenderId: '222984423696',
    projectId: 'nagaoka-list-items-dbc68',
    authDomain: 'nagaoka-list-items-dbc68.firebaseapp.com',
    storageBucket: 'nagaoka-list-items-dbc68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRhxC6AcyrbrdqAJMAMrX33FiRrQkt-QY',
    appId: '1:222984423696:android:cfdeb9b53dcca97d0c7d95',
    messagingSenderId: '222984423696',
    projectId: 'nagaoka-list-items-dbc68',
    storageBucket: 'nagaoka-list-items-dbc68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOtglOrICTaOHCqlssw0yScrlvAedcDA4',
    appId: '1:222984423696:ios:0fd5ae0bbffd260a0c7d95',
    messagingSenderId: '222984423696',
    projectId: 'nagaoka-list-items-dbc68',
    storageBucket: 'nagaoka-list-items-dbc68.appspot.com',
    iosBundleId: 'com.nagaoka.nagaokaListItems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOtglOrICTaOHCqlssw0yScrlvAedcDA4',
    appId: '1:222984423696:ios:0fd5ae0bbffd260a0c7d95',
    messagingSenderId: '222984423696',
    projectId: 'nagaoka-list-items-dbc68',
    storageBucket: 'nagaoka-list-items-dbc68.appspot.com',
    iosBundleId: 'com.nagaoka.nagaokaListItems',
  );
}
